### PR TITLE
Pointer re-lock, non-VR stylesheet in VR. 

### PR DESCRIPTION
**Pull request by SanderVanhove**
Hello!

I'm pretty new to GidHub, and open source in general. This is my first pull request ever. I'm working with your library and added 2 small changes to get in to it a little bit.

The first is to re-request pointerlock when the pointerlock is lost in VR (by pressing Esc) and the user clicks on the canvas.
The seconde enables the user to define a stylsheet that will be applied to the non-VR page when in VR. And made an example of this in the index.html (it's very small). 

Lastly I made a small Wiki page on my fork that I will try to keep up to date and expand as necessary. I made it for myself, but I guess others can find it helpful as wel: https://github.com/Lamasaurus/html2three/wiki

### CODE REVIEW

**Review by marciot — CHANGES_REQUESTED** [review]
Hi Lamasaurus, thank you for these suggestions. These are great, thank you.

However there is one major issue and one minor issue. The major issue is you made changes to the "dist-ecma5" files. These files are generated by compilation using the Babel tool (https://babeljs.io) from the source files in "src-ecma6" and get overwritten. I'm sorry I did not make this clear.

Here is why I use Babel: the files in "src-ecma6" are easier to understand and read because they use the new Javascript 6 "class" syntax. That is not compatible with all browsers, so Babel allows me to compile those differences away.

Would you be able to make your changes to "src-ecma6" instead? Do not worry about running babel (unless you want). I can run Babel to generate the corresponding "dist-ecma5" files.

Now these two issues are minor:
  - There is a typing error in the name "useVrOnlyrStylesheet". It should be spelled "useVrOnlyStylesheet"
  - I do not think the comment in "index.html" should be removed. It is there to explain why I used visibility hidden rather than "display: none". 

Thank you for your contribution! You say it is the first time you made a pull request, well this is the first time I got to review one for this project. You are my first contributor :)

**Comment by SanderVanhove** [comment]
Hey Marciot.

I'll make those changes. They are not that big, so its doable in an hour or so. No problem! Thanks for taking the time to clarify this.

I'm using this library in my bachelor thesis. It will depending on my promotor if I'll use it more and make more contributions.

But I think this project is to hard to find! I found it by accident on this list: https://github.com/wizztjh/awesome-WebVR 
While it is a pretty amazing tool ;)

**Comment by SanderVanhove** [comment]
Done!
Changed everything you asked for.

**Comment by marciot** [comment]
Awesome, all merged. Thank you so much!

I added it to the awesome-WebVR list, so that's how you found it there ;)

Glad you are finding the library to be useful in your thesis, do you mind me asking what your project is and what hardware you are targeting?

Do be aware that the library is not GearVR compatible (clicking does not work). I believe the problem can be fixed, but since I don't own a Gear, it is hard for me to do so.

One quick question, on line 206, you wrap the expression in void. I was not familiar with that construct. What is this for? I assumed a function was normally void unless it had a "return" statement.

-- Marcio

**Comment by SanderVanhove** [comment]
Haha, good that you did that ;)

I have to research how to make sites VR ready with as less effort as possible and how to make sites purely made for VR. And this method is good for the first case. I think I'll be using A-frame for the seconde case.

And I also have no GearVR, but I don't think that it will be a problem.

The void() call is a sort of a try{}catch{}, it won't error when the expression that it is given is wrong (like if the stylesheet didn't have a disabled property, didn't exist). It also always gives an 'undefined' object back. But it is actual redundant here because I already check for it in the if test. I'll delete that in my next commit.

Sander

**Pull request merged**
